In [3]:
import json
import pandas as pd

with open("advertisers_using_your_activity_or_information.json") as file:
    data = json.load(file)

In [4]:
type(data)

dict

In [6]:
data.keys()

dict_keys(['media', 'label_values', 'fbid'])

In [7]:
advertisers = data["label_values"][0]["vec"]

In [8]:
type(advertisers)

list

In [9]:
advertisers[0]

{'value': 'Indeed'}

In [11]:
pd.DataFrame(advertisers)

                          value
0                        Indeed
1                   NOCAP, Inc.
2            MediaCom Melbourne
3                  Brother Sews
4                    SharkNinja
...                         ...
4778                Royle Media
4779               Judge & Jury
4780                 Fox 8 News
4781  Prospector Baseball Group
4782            Kleen Nutrition

[4783 rows x 1 columns]

In [13]:
df = pd.DataFrame(advertisers)
df.head()

                value
0              Indeed
1         NOCAP, Inc.
2  MediaCom Melbourne
3        Brother Sews
4          SharkNinja

In [15]:
df = df.rename(
    columns={"value": "advertiser_name"})

In [16]:
df.head()

      advertiser_name
0              Indeed
1         NOCAP, Inc.
2  MediaCom Melbourne
3        Brother Sews
4          SharkNinja

In [23]:
df.shape

(4783, 1)

In [18]:
df.tail()

                advertiser_name
4778                Royle Media
4779               Judge & Jury
4780                 Fox 8 News
4781  Prospector Baseball Group
4782            Kleen Nutrition

In [19]:
df.columns

Index(['advertiser_name'], dtype='str')

In [21]:
df.info

<bound method DataFrame.info of                 advertiser_name
0                        Indeed
1                   NOCAP, Inc.
2            MediaCom Melbourne
3                  Brother Sews
4                    SharkNinja
...                         ...
4778                Royle Media
4779               Judge & Jury
4780                 Fox 8 News
4781  Prospector Baseball Group
4782            Kleen Nutrition

[4783 rows x 1 columns]>

In [24]:
len(df)

4783

In [26]:
df["advertiser_name"].nunique()

4783

In [28]:
golf_ads = df[df["advertiser_name"].str.contains("golf")]

In [29]:
golf_ads

             advertiser_name
488                  Topgolf
678   Pins and aces golf co.
1118    clubhousegolfcompany
1135           traplinksgolf
1298           thegolfarmory
2259           pounddiscgolf
2704               head golf
2915     backswinggolfevents
3049              cesky.golf
3284      hellforleathergolf
3312          thesaltygolfer
3502             shankitgolf
3544           Dingersgolfco
3938            zaleasgolfco
4737         golfcreatoropen