In [1]:
import json
import pandas as pd

with open('liked_posts.json', 'r') as f:
    data = json.load(f)

data[0]

{'timestamp': 1788114943,
 'media': [],
 'label_values': [{'label': 'URL',
   'value': 'https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0QFnlDamOwbYfoZVfzs8s0/',
   'href': 'https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0QFnlDamOwbYfoZVfzs8s0/'},
  {'label': 'Caption', 'value': 'Smiling because itâ\x80\x99s Sunday!'},
  {'label': 'Title', 'value': ''},
  {'dict': [], 'title': 'Hashtags'},
  {'dict': [{'dict': [{'label': 'URL', 'value': ''},
      {'label': 'Name', 'value': 'Sophie Peerless'},
      {'label': 'Username', 'value': 'sophie_peerless08'}],
     'title': ''}],
   'title': 'Owner'},
  {'dict': [], 'title': 'Brand partner'}],
 'fbid': '18037111067834578'}

In [2]:
row = {}
row['timestamp'] = data[0]['timestamp']

row

{'timestamp': 1788114943}

In [7]:
for item in data[0]['label_values']:
    if 'label' in item:
        row[item['label']] = item['value']

row

{'URL': 'https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0QFnlDamOwbYfoZVfzs8s0/',
 'Caption': 'Smiling because itâ\x80\x99s Sunday!',
 'Title': ''}

In [16]:
for item in data[0]['label_values']:
    if 'label' in item:
        row[item['label']] = item['value']
    elif item.get('title') == 'Owner':
        owner_fields = item['dict'][0]['dict']
        for owner_item in owner_fields:
            row['Owner ' + owner_item['label']] = owner_item['value']

row

{'URL': '',
 'Caption': 'Smiling because itâ\x80\x99s Sunday!',
 'Title': '',
 'Owner URL': '',
 'Owner Name': 'Sophie Peerless',
 'Owner Username': 'sophie_peerless08',
 'Name': 'Sophie Peerless',
 'Username': 'sophie_peerless08'}

In [19]:
tidy_rows = []

for entry in data:
    row = {}
    row['timestamp'] = entry['timestamp']
    
    for item in entry['label_values']:
        if 'label' in item:
            row[item['label']] = item['value']
        elif item.get('title') == 'Owner':
            owner_fields = item['dict'][0]['dict']
            for owner_item in owner_fields:
                row['Owner ' + owner_item['label']] = owner_item['value']
    tidy_rows.append(row)

tidy_rows[:2]

[{'timestamp': 1788114943,
  'URL': 'https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0QFnlDamOwbYfoZVfzs8s0/',
  'Caption': 'Smiling because itâ\x80\x99s Sunday!',
  'Title': '',
  'Owner URL': '',
  'Owner Name': 'Sophie Peerless',
  'Owner Username': 'sophie_peerless08'},
 {'timestamp': 1788086270,
  'URL': 'https://www.instagram.com/p/Dcn-TKdDjwY/',
  'Caption': 'What a great night for our Par 3 Food Truck event! Capped off by a 9 Hole Putting contest under the lights. \n\n- Hole In One Alert on #8ð\x9f\x9a¨ Kelley Mehallis -',
  'Title': '',
  'Owner URL': 'https://charity.pledgeit.org/c/B4QRc389rO',
  'Owner Name': 'Walden Golf Shop',
  'Owner Username': 'waldengolfshop'}]

In [20]:
likes_df = pd.DataFrame(tidy_rows)
likes_df.head(10)

,timestamp,URL,Caption,Title,Owner URL,Owner Name,Owner Username
0,1788114943,https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0...,Smiling because itâs Sunday!,,,Sophie Peerless,sophie_peerless08
1,1788086270,https://www.instagram.com/p/Dcn-TKdDjwY/,What a great night for our Par 3 Food Truck ev...,,https://charity.pledgeit.org/c/B4QRc389rO,Walden Golf Shop,waldengolfshop
2,1788057327,https://www.instagram.com/p/DcoUHKKDn2p/,Some photos from last nightâs Couples Twilig...,,http://www.portagecc.org/,Portage Country Club,portagecountryclub
3,1788056601,https://www.instagram.com/p/DcpQPLzgJbn/,Great day at Buckeye Bot Bash 2 today! I canâ...,,,Nathan Milhorn,8snoman8
4,1787952264,https://www.instagram.com/p/DcmQ-5NIhcH/,"á´á´É´á´, Éªá´âê± ê°ÊÉªá´ á´Ê.\ná´...",,,Beware of The Leopard Kent,bewareoftheleopardkent
5,1787947692,https://www.instagram.com/p/DcmKrwOgAIi/,Feeling like I should call this colorâMaple ...,,http://www.goodcosalon.com/,Erica Evans,ericaevans.hair
6,1787933042,https://www.instagram.com/p/Dcloqx1DrLA/,"Surgeons, engineers, teachers and more! ð¤ T...",,,United States Golf Association,usga
7,1787927416,https://www.instagram.com/p/DckBC_4uqKG/,Thursday Night Football by the lake. #gobrowns...,,,Jared Simon,jaredlsimon
8,1787922955,https://www.instagram.com/p/DclZAPFlr26/,Informational Meeting tonight! \nAugust 28th @...,,https://popup.doublegood.com/s/ts8r17c0,Kent State Vex Robotics Team,kent_state_robotics_team
9,1787920432,https://www.instagram.com/p/DclXFbzuIUeSPcRzLf...,Woodrow Jacques. Born August 23rd 2026. ð,,,jocelyn,jcbonn

In [22]:
likes_df['DateTime'] = pd.to_datetime(likes_df['timestamp'], unit='s')
likes_df[['timestamp', 'DateTime']].head()

    timestamp            DateTime
0  1788114943 2026-08-30 18:35:43
1  1788086270 2026-08-30 10:37:50
2  1788057327 2026-08-30 02:35:27
3  1788056601 2026-08-30 02:23:21
4  1787952264 2026-08-28 21:24:24

In [23]:
likes_df.head(10)

,timestamp,URL,Caption,Title,Owner URL,Owner Name,Owner Username,DateTime
0,1788114943,https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0...,Smiling because itâs Sunday!,,,Sophie Peerless,sophie_peerless08,2026-08-30 18:35:43
1,1788086270,https://www.instagram.com/p/Dcn-TKdDjwY/,What a great night for our Par 3 Food Truck ev...,,https://charity.pledgeit.org/c/B4QRc389rO,Walden Golf Shop,waldengolfshop,2026-08-30 10:37:50
2,1788057327,https://www.instagram.com/p/DcoUHKKDn2p/,Some photos from last nightâs Couples Twilig...,,http://www.portagecc.org/,Portage Country Club,portagecountryclub,2026-08-30 02:35:27
3,1788056601,https://www.instagram.com/p/DcpQPLzgJbn/,Great day at Buckeye Bot Bash 2 today! I canâ...,,,Nathan Milhorn,8snoman8,2026-08-30 02:23:21
4,1787952264,https://www.instagram.com/p/DcmQ-5NIhcH/,"á´á´É´á´, Éªá´âê± ê°ÊÉªá´ á´Ê.\ná´...",,,Beware of The Leopard Kent,bewareoftheleopardkent,2026-08-28 21:24:24
5,1787947692,https://www.instagram.com/p/DcmKrwOgAIi/,Feeling like I should call this colorâMaple ...,,http://www.goodcosalon.com/,Erica Evans,ericaevans.hair,2026-08-28 20:08:12
6,1787933042,https://www.instagram.com/p/Dcloqx1DrLA/,"Surgeons, engineers, teachers and more! ð¤ T...",,,United States Golf Association,usga,2026-08-28 16:04:02
7,1787927416,https://www.instagram.com/p/DckBC_4uqKG/,Thursday Night Football by the lake. #gobrowns...,,,Jared Simon,jaredlsimon,2026-08-28 14:30:16
8,1787922955,https://www.instagram.com/p/DclZAPFlr26/,Informational Meeting tonight! \nAugust 28th @...,,https://popup.doublegood.com/s/ts8r17c0,Kent State Vex Robotics Team,kent_state_robotics_team,2026-08-28 13:15:55
9,1787920432,https://www.instagram.com/p/DclXFbzuIUeSPcRzLf...,Woodrow Jacques. Born August 23rd 2026. ð,,,jocelyn,jcbonn,2026-08-28 12:33:52

In [24]:
likes_df.shape

(28784, 8)

In [25]:
likes_df['Owner Username'].isna().sum()

np.int64(0)

In [26]:
likes_df.dtypes

timestamp                 int64
URL                         str
Caption                     str
Title                       str
Owner URL                   str
Owner Name                  str
Owner Username              str
DateTime          datetime64[s]
dtype: object

In [27]:
likes_df.groupby("Owner Username")["DateTime"].count()

Owner Username
0handicap            1
12courtlynn         13
12szippla            5
1brooketaylor       13
1mbseriestennis      1
                  ...
zipswgolf           16
ziregolf           102
zoeefaure            1
zoeforman            1
zwhite1128551        4
Name: DateTime, Length: 1978, dtype: int64

In [29]:
likes_by_account = (
    likes_df.groupby("Owner Username")["DateTime"]
    .count()
    .sort_values(ascending=False)
)
likes_by_account.head(10)

Owner Username
samanthahudeck      680
mytherapistsays     491
pgamemes            428
nohiopga            421
golfdigest          378
_kendrabee_         367
kiera.kurak         321
jessmccartney216    271
pgatour             245
wordporm            244
Name: DateTime, dtype: int64