I would answer my questions here

In [1]:
import json
import pandas as pd

with open("liked_posts.json", "r") as file:
    liked_posts = json.load(file)

liked_posts[0]

{'timestamp': 1788114943,
 'media': [],
 'label_values': [{'label': 'URL',
   'value': 'https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0QFnlDamOwbYfoZVfzs8s0/',
   'href': 'https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0QFnlDamOwbYfoZVfzs8s0/'},
  {'label': 'Caption', 'value': 'Smiling because itâ\x80\x99s Sunday!'},
  {'label': 'Title', 'value': ''},
  {'dict': [], 'title': 'Hashtags'},
  {'dict': [{'dict': [{'label': 'URL', 'value': ''},
      {'label': 'Name', 'value': 'Sophie Peerless'},
      {'label': 'Username', 'value': 'sophie_peerless08'}],
     'title': ''}],
   'title': 'Owner'},
  {'dict': [], 'title': 'Brand partner'}],
 'fbid': '18037111067834578'}

In [2]:
likes_df = pd.DataFrame(liked_posts)

likes_df.head()

,timestamp,media,label_values,fbid
0,1788114943,[],"[{'label': 'URL', 'value': 'https://www.instag...",18037111067834578
1,1788086270,[],"[{'label': 'URL', 'value': 'https://www.instag...",18093005174640259
2,1788057327,[],"[{'label': 'URL', 'value': 'https://www.instag...",17893857291603847
3,1788056601,[],"[{'label': 'URL', 'value': 'https://www.instag...",18183334627412241
4,1787952264,[],"[{'label': 'URL', 'value': 'https://www.instag...",17961158849980305

In [3]:
liked_posts[0]["timestamp"]

1788114943

In [4]:
liked_posts[0]["label_values"]

[{'label': 'URL',
  'value': 'https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0QFnlDamOwbYfoZVfzs8s0/',
  'href': 'https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0QFnlDamOwbYfoZVfzs8s0/'},
 {'label': 'Caption', 'value': 'Smiling because itâ\x80\x99s Sunday!'},
 {'label': 'Title', 'value': ''},
 {'dict': [], 'title': 'Hashtags'},
 {'dict': [{'dict': [{'label': 'URL', 'value': ''},
     {'label': 'Name', 'value': 'Sophie Peerless'},
     {'label': 'Username', 'value': 'sophie_peerless08'}],
    'title': ''}],
  'title': 'Owner'},
 {'dict': [], 'title': 'Brand partner'}]

In [5]:
liked_posts[0]["label_values"][0]

{'label': 'URL',
 'value': 'https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0QFnlDamOwbYfoZVfzs8s0/',
 'href': 'https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0QFnlDamOwbYfoZVfzs8s0/'}

In [6]:
liked_posts[0]["label_values"][1]

{'label': 'Caption', 'value': 'Smiling because itâ\x80\x99s Sunday!'}

In [7]:
liked_posts[0]["label_values"][2]

{'label': 'Title', 'value': ''}

In [8]:
liked_posts[0]["label_values"][3]

{'dict': [], 'title': 'Hashtags'}

In [9]:
liked_posts[0]["label_values"][4]

{'dict': [{'dict': [{'label': 'URL', 'value': ''},
    {'label': 'Name', 'value': 'Sophie Peerless'},
    {'label': 'Username', 'value': 'sophie_peerless08'}],
   'title': ''}],
 'title': 'Owner'}

In [10]:
type(liked_posts[0]["label_values"][4])

dict

In [11]:
liked_posts[0]["label_values"][4]["dict"][0]

{'dict': [{'label': 'URL', 'value': ''},
  {'label': 'Name', 'value': 'Sophie Peerless'},
  {'label': 'Username', 'value': 'sophie_peerless08'}],
 'title': ''}

In [12]:
liked_posts[0]["label_values"][4]["dict"][0]["dict"]

[{'label': 'URL', 'value': ''},
 {'label': 'Name', 'value': 'Sophie Peerless'},
 {'label': 'Username', 'value': 'sophie_peerless08'}]

In [13]:
liked_posts[0]["label_values"][4]["dict"][0]["dict"][0]

{'label': 'URL', 'value': ''}

In [18]:
liked_posts[0]["label_values"][4]["dict"][0]["dict"][1]["value"]

'Sophie Peerless'

In [19]:
liked_posts[0]["label_values"][4]["dict"][0]["dict"][2]["value"]

'sophie_peerless08'

In [21]:
likes_df = pd.DataFrame(liked_posts)

likes_df.head()

,timestamp,media,label_values,fbid
0,1788114943,[],"[{'label': 'URL', 'value': 'https://www.instag...",18037111067834578
1,1788086270,[],"[{'label': 'URL', 'value': 'https://www.instag...",18093005174640259
2,1788057327,[],"[{'label': 'URL', 'value': 'https://www.instag...",17893857291603847
3,1788056601,[],"[{'label': 'URL', 'value': 'https://www.instag...",18183334627412241
4,1787952264,[],"[{'label': 'URL', 'value': 'https://www.instag...",17961158849980305

In [24]:
tidy_likes = []

for post in liked_posts:
    timestamp = post["timestamp"]
    caption = ""
    name = ""
    username = ""

    for item in post["label_values"]:

        if item.get("label") == "Caption":
            caption = item["value"]

        if item.get("title") == "Owner":
            owner = item["dict"][0]["dict"]

            for detail in owner:
                if detail["label"] == "Name":
                    name = detail["value"]

                if detail["label"] == "Username":
                    username = detail["value"]

    tidy_likes.append({
        "timestamp": timestamp,
        "caption": caption,
        "name": name,
        "username": username
    })

In [26]:
likes_df = pd.DataFrame(tidy_likes)

likes_df["timestamp"] = pd.to_datetime(
likes_df["timestamp"],
unit="s"
)

likes_df.head()

,timestamp,caption,name,username
0,2026-08-30 18:35:43,Smiling because itâs Sunday!,Sophie Peerless,sophie_peerless08
1,2026-08-30 10:37:50,What a great night for our Par 3 Food Truck ev...,Walden Golf Shop,waldengolfshop
2,2026-08-30 02:35:27,Some photos from last nightâs Couples Twilig...,Portage Country Club,portagecountryclub
3,2026-08-30 02:23:21,Great day at Buckeye Bot Bash 2 today! I canâ...,Nathan Milhorn,8snoman8
4,2026-08-28 21:24:24,"á´á´É´á´, Éªá´âê± ê°ÊÉªá´ á´Ê.\ná´...",Beware of The Leopard Kent,bewareoftheleopardkent

In [27]:
likes_df.groupby("username").count()

                 timestamp  caption  name
username
0handicap                1        1     1
12courtlynn             13       13    13
12szippla                5        5     5
1brooketaylor           13       13    13
1mbseriestennis          1        1     1
...                    ...      ...   ...
zipswgolf               16       16    16
ziregolf               102      102   102
zoeefaure                1        1     1
zoeforman                1        1     1
zwhite1128551            4        4     4

[1978 rows x 3 columns]

In [37]:
timestamps = [
    post["timestamp"]
    for post in liked_posts
]

captions = [
    post["label_values"][1]["value"]
    for post in liked_posts
]

usernames = [
    post["label_values"][4]["dict"][0]["dict"][2]["value"]
    for post in liked_posts
]

likes_df = pd.DataFrame({
    "timestamp": timestamps,
    "caption": captions,
    "username": usernames
})

likes_df["timestamp"] = pd.to_datetime(
    likes_df["timestamp"],
    unit="s"
)

likes_df.head()

KeyError: 'value'

In [38]:
timestamps = []
captions = []
usernames = []

for post in liked_posts:
    
    timestamp = post["timestamp"]
    caption = ""
    username = ""
    
    for item in post["label_values"]:
        
        if item.get("label") == "Caption":
            caption = item.get("value", "")
            
        if item.get("title") == "Owner":
            for owner in item.get("dict", []):
                for detail in owner.get("dict", []):
                    if detail.get("label") == "Username":
                        username = detail.get("value", "")
    
    timestamps.append(timestamp)
    captions.append(caption)
    usernames.append(username)


likes_df = pd.DataFrame({
    "timestamp": timestamps,
    "caption": captions,
    "username": usernames
})


likes_df["timestamp"] = pd.to_datetime(
    likes_df["timestamp"],
    unit="s"
)


likes_df.head()

,timestamp,caption,username
0,2026-08-30 18:35:43,Smiling because itâs Sunday!,sophie_peerless08
1,2026-08-30 10:37:50,What a great night for our Par 3 Food Truck ev...,waldengolfshop
2,2026-08-30 02:35:27,Some photos from last nightâs Couples Twilig...,portagecountryclub
3,2026-08-30 02:23:21,Great day at Buckeye Bot Bash 2 today! I canâ...,8snoman8
4,2026-08-28 21:24:24,"á´á´É´á´, Éªá´âê± ê°ÊÉªá´ á´Ê.\ná´...",bewareoftheleopardkent

In [36]:
likes_by_account = (
    likes_df.groupby("username")["timestamp"]
    .count()
    .sort_values(ascending=False)
)

likes_by_account.head(10)

username
samanthahudeck      680
mytherapistsays     491
pgamemes            428
nohiopga            421
golfdigest          378
_kendrabee_         367
kiera.kurak         321
jessmccartney216    271
pgatour             245
wordporm            244
Name: timestamp, dtype: int64

In [39]:
likes_df["date"] = likes_df["timestamp"].dt.date
likes_df["day_of_week"] = likes_df["timestamp"].dt.day_name()
likes_df["hour"] = likes_df["timestamp"].dt.hour

In [42]:
likes_df.groupby("day_of_week")["timestamp"].count().sort_values(ascending=False)

day_of_week
Sunday       5043
Saturday     4273
Monday       4217
Friday       3886
Thursday     3876
Wednesday    3767
Tuesday      3722
Name: timestamp, dtype: int64

In [43]:
likes_df.groupby(["date", "username"])["timestamp"].count()

date        username
2012-12-27  katerintree           1
            katy_avon             1
            kcretin               1
2012-12-28  bethannesbest         1
            hollyjean331          1
                                 ..
2026-08-28  usga                  1
2026-08-30  8snoman8              1
            portagecountryclub    1
            sophie_peerless08     1
            waldengolfshop        1
Name: timestamp, Length: 26562, dtype: int64